name: Run Pytest on Windows

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main  # Führt die Tests bei jedem Pull Request auf den main-Branch aus

jobs:
  test:
    runs-on: windows-latest  # Windows-Runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Wähle die Python-Version aus, die du benötigst

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: pytest tests
